import React, { useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BarChart3, Calendar, FileText, Home, LogOut, Menu, Plus, Receipt, Search, Users, Wallet, TrendingDown, Building2, Bell, Sun, Moon, ClipboardCheck } from 'lucide-react'
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, PieChart, Pie, Cell } from 'recharts'
import { hasSupabaseConfig } from './lib/supabase'
import { monthly, expenses, invoices, activity } from './data/mockData'
import './styles.css'

const menu = [
  { group:'Principal', items:[['Dashboard',Home,'dashboard']] },
  { group:'Finanzas', items:[['Ingresos',Wallet,'ingresos'],['Gastos',TrendingDown,'gastos'],['Facturas',Receipt,'facturas'],['Cotizaciones',ClipboardCheck,'cotizaciones']] },
  { group:'Gestión', items:[['Clientes',Users,'clientes'],['Calendario',Calendar,'calendario'],['Reportes',BarChart3,'reportes']] },
  { group:'Recursos Humanos', items:[['Empresas RH',Building2,'rrhh']] },
  { group:'Documentos RRHH', items:[['Generar Documentos',FileText,'documentos']] }
]

function money(n){return new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(n||0)}
function Sidebar({page,setPage,open,setOpen}){return <aside className={`sidebar ${open?'open':''}`}><div className="brand"><img src="/icon-192.png" onError={e=>e.currentTarget.style.display='none'}/><div><strong>Segura Contable</strong><small>Portal profesional</small></div></div><nav className="nav">{menu.map(g=><React.Fragment key={g.group}><div className="group">{g.group}</div>{g.items.map(([label,Icon,id])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setOpen(false)}}><Icon size={18}/>{label}</button>)}</React.Fragment>)}</nav><div className="user"><div className="avatar">S</div><div><strong>Segura Contable</strong><br/><small>Administrador</small></div></div></aside>}
function Topbar({title,setOpen,dark,setDark}){return <header className="topbar"><button className="btn mobile-toggle" onClick={()=>setOpen(true)}><Menu size={18}/></button><div className="title">{title}</div><div className="top-actions"><button className="btn" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><button className="btn"><LogOut size={15}/> Salir</button><button className="btn"><Bell size={18}/></button><button className="btn primary"><Plus size={17}/> Nuevo</button></div></header>}
function Metric({label,value,type}){return <div className={`card metric ${type||''}`}><div className="label">{label}</div><div className="value">{value}</div></div>}
function Dashboard(){const ingresos=monthly.reduce((a,b)=>a+b.ingresos,0), gastos=monthly.reduce((a,b)=>a+b.gastos,0), porCobrar=invoices.filter(i=>i.estado!=='Pagada').reduce((a,b)=>a+b.monto,0);return <><div className="metrics"><Metric label="Ingresos del mes" value={money(ingresos)} /><Metric label="Gastos del mes" value={money(gastos)} type="blue"/><Metric label="Utilidad neta" value={money(ingresos-gastos)} type="green"/><Metric label="Por cobrar" value={money(porCobrar)} type="amber"/></div><div className="grid"><div className="card chart-card"><div className="chart-title">Ingresos vs Gastos 2026</div><ResponsiveContainer width="100%" height={240}><BarChart data={monthly}><XAxis dataKey="month"/><YAxis tickFormatter={v=>`${Math.round(v/1000000)}M`}/><Tooltip formatter={v=>money(v)}/><Bar dataKey="ingresos" radius={[8,8,0,0]}/><Bar dataKey="gastos" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div><div className="card chart-card"><div className="chart-title">Distribución Gastos</div><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={expenses} dataKey="value" nameKey="name" innerRadius={58} outerRadius={88}>{expenses.map((_,i)=><Cell key={i}/>)}</Pie><Tooltip formatter={v=>money(v)}/></PieChart></ResponsiveContainer></div></div><div className="section"><div className="card page-card"><div className="chart-title">Últimas Facturas</div><table className="table"><thead><tr><th>Cliente</th><th>Monto</th><th>Vencimiento</th><th>Estado</th></tr></thead><tbody>{invoices.map(f=><tr key={f.cliente}><td>{f.cliente}</td><td>{money(f.monto)}</td><td>{f.vencimiento}</td><td><span className="badge">{f.estado}</span></td></tr>)}</tbody></table></div><div className="card page-card"><div className="chart-title">Actividad Reciente</div><div className="list">{activity.map(a=><div className="list-item" key={a}>{a}<span>→</span></div>)}</div></div></div></>}
function ModulePage({name,kind}){return <div className="card page-card"><div className="chart-title">{name}</div><p>Base modular lista para conectar a Supabase. {hasSupabaseConfig?'Supabase detectado por variables de entorno.':'Configura VITE_SUPABASE_URL y VITE_SUPABASE_ANON_KEY en Netlify para activar conexión.'}</p><div className="toolbar"><input className="input" placeholder={`Buscar en ${name.toLowerCase()}...`}/><button className="btn primary"><Plus size={16}/> Nuevo registro</button><button className="btn"><Search size={16}/> Filtrar</button></div><div className="list">{['Registro ejemplo 1','Registro ejemplo 2','Registro ejemplo 3'].map((x,i)=><div className="list-item" key={x}><div><strong>{x}</strong><br/><small>{kind} · preparado para CRUD</small></div><span className="badge">Activo</span></div>)}</div></div>}
function App(){const [page,setPage]=useState('dashboard'), [open,setOpen]=useState(false), [dark,setDark]=useState(false);const titles={dashboard:'Dashboard',ingresos:'Ingresos',gastos:'Gastos',facturas:'Facturas',cotizaciones:'Cotizaciones',clientes:'Clientes',calendario:'Calendario',reportes:'Reportes',rrhh:'Empresas RH',documentos:'Generar Documentos'};const content=useMemo(()=>page==='dashboard'?<Dashboard/>:<ModulePage name={titles[page]} kind={page}/>,[page]);return <div className="app" data-theme={dark?'dark':'light'}><Sidebar page={page} setPage={setPage} open={open} setOpen={setOpen}/><main className="main"><Topbar title={titles[page]} setOpen={setOpen} dark={dark} setDark={setDark}/><div className="content">{content}</div></main></div>}

createRoot(document.getElementById('root')).render(<App />)
